---
title: "Relatório mensal de Crescimento"
output:
  html_document: default
  pdf_document: default
date: "`r format(Sys.time(), '%d %B, %Y')`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

```{r bibliotecas, include=FALSE}
#Relatório mensal de vendas

if (!require(dplyr)) install.packages("dplyr")
if (!require(readr)) install.packages("readr")
if (!require(ggplot2)) install.packages("ggplot2")
if (!require(plotly)) install.packages("plotly")
if (!require(readxl)) install.packages("readxl")
if (!require(lubridate)) install.packages("lubridate")
if (!require(zoo)) install.packages("zoo")
if (!require(sunburstR)) install.packages("sunberstR")
if (!require(forecast)) install.packages("forecast")
if (!require(stringr)) install.packages("stringr")
```


```{r vendas semestre, echo=FALSE, message=FALSE, warning=FALSE, results = "hide"}
pipe_FunildeVendas<- read_delim("pipe Funil de Vendas.csv", ";", escape_double = FALSE, locale = locale(), 
                                  trim_ws = TRUE)
not_all_na <- function(x) {!all(is.na(x))}

pipe_FunildeVendas <- pipe_FunildeVendas %>% select_if(not_all_na)

important_columns <- c("ID", 
                       "Pipeline",
                       "Fase",
                       "Responsável", 
                       "Nome do negócio", 
                       "Tipo", 
                       "Renda",
                       "Empresa", 
                       "Data de início", 
                       "Data de fechamento",
                       "Produto",
                       "Origem da Oportunidade", 
                       "Deal de:" )

pipe_FunildeVendas <- subset.data.frame(pipe_FunildeVendas, select= important_columns)

pipe_FunildeVendas <- pipe_FunildeVendas[!is.na(pipe_FunildeVendas$Pipeline) & pipe_FunildeVendas$Pipeline == "Funil de vendas",]
pipe_FunildeVendas$`Data de fechamento` <- as.Date(x = pipe_FunildeVendas$`Data de fechamento`, format = "%d/%m/%Y")
pipe_FunildeVendas$`Data de início` <- as.Date(x = pipe_FunildeVendas$`Data de início`, format = "%d/%m/%Y")
pipe_FunildeVendas$"endQuarter" <- quarters(pipe_FunildeVendas$`Data de fechamento`) 
pipe_FunildeVendas$"startQuarter" <- quarters(pipe_FunildeVendas$`Data de fechamento`)
pipe_FunildeVendas$Renda <- as.numeric(pipe_FunildeVendas$Renda)
pipe_FunildeVendas %>% 
  mutate_at(vars(Renda), funs(round(x = ., digits = 0)))

QuarterSales <- pipe_FunildeVendas%>%
  filter(Fase == "Ganho Fechado")
  
QuarterSalesSum <- QuarterSales %>% 
  group_by(`endQuarter`, Ano = format(`Data de fechamento`, "%Y" )) %>%
  summarise(Renda = sum(Renda)) 
 
 QuarterSalesSum <- QuarterSalesSum %>% 
  mutate(Rendaper1000 = Renda/1000 ) 
 
QuarterSalesSum$Rendaper1000 <- round(QuarterSalesSum$Rendaper1000, 0)

Q1SalesSum <- QuarterSalesSum %>% 
  filter(endQuarter == "Q2" & Ano != 2017)

ggplot(data = Q1SalesSum, mapping = aes(x = Q1SalesSum$Ano, y = Q1SalesSum$Rendaper1000, label = Q1SalesSum$Rendaper1000))+
  geom_col(fill = "red", color = "black") +
  geom_text(size = 4,position = position_stack(vjust = 1.1)) +
  ylab("Renda em milhares de R$") +
  xlab("Ano") +
  ggtitle("Renda no 2º trimestre de cada ano" )

```
  
  Este ano já conseguimos ter 50% das vendas do ano passado para o mesmo trimestre. 
  
  
```{r vendas mensal,  echo=FALSE, message=FALSE, warning=FALSE, results = "hide"}

MonthSales <- pipe_FunildeVendas %>%
  filter(Fase == "Ganho Fechado")

MonthSales <- MonthSales %>% 
  rename ("Deal_de" = `Deal de:`)

MonthSalesSum <- MonthSales %>% 
  group_by("Data_de_fechamento" = month(`Data de fechamento`), Ano = format(`Data de fechamento`, "%Y" )) %>%
  summarise(Renda = sum(Renda))

 MonthSalesSum <- MonthSalesSum %>% 
  mutate(Rendaper1000 = Renda/1000 ) 
 
 MonthSalesSum$Rendaper1000 <- round(MonthSalesSum$Rendaper1000, 0)
 
 AbrilSalesSum <- MonthSalesSum %>% 
  filter(Data_de_fechamento == (month(Sys.Date())-1) & Ano > (year(Sys.Date())-3))

ggplot(data = AbrilSalesSum, mapping = aes(x = AbrilSalesSum$Ano, y = AbrilSalesSum$Rendaper1000, label = AbrilSalesSum$Rendaper1000))+
  geom_col(fill = "red", color = "black") +
  geom_text(size = 4,position = position_stack(vjust = 1.1)) +
  ylab("Renda em milhares de R$") +
  xlab("Ano") +
  ggtitle(sprintf("Renda em %s de cada ano", month(Sys.Date()-month(1), label = TRUE, abbr = FALSE)))
```
  
  Olhando especificamente para maio nós conseguimos uma venda superior à do ano passado, mesmo durante uma crise. 
  Cabe uma análise por produto
```{r echo=FALSE, message=FALSE, warning=FALSE}
SalesSumbyMonthandDeal <- MonthSales %>% 
  group_by(Deal_de, "Data_de_fechamento" = month(`Data de fechamento`), Ano = format(`Data de fechamento`, "%Y" ) ) %>%
  summarise(Renda = sum(Renda))

SalesSumbyMonthandDeal <- SalesSumbyMonthandDeal %>% 
  mutate(Rendaper1000 = Renda/1000 ) 
 
SalesSumbyMonthandDeal$Rendaper1000 <- round(SalesSumbyMonthandDeal$Rendaper1000, 0)
 
ThisMonthSalesSum <- SalesSumbyMonthandDeal %>% 
  filter(Data_de_fechamento == (month(Sys.Date())-1) & Ano > (year(Sys.Date())-3))

```

```{r sunburst, eval=FALSE, message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
ThisMonthSalesSumSunburst <- read_delim("ThisMonthSalesSum.csv", 
    ";", escape_double = FALSE, locale = locale(encoding = "ISO-8859-1"), 
    trim_ws = TRUE)
ThisMonthSalesSumjson <- ThisMonthSalesSumSunburst[,5:6]

sunburst(data = ThisMonthSalesSumjson, percent = TRUE, count = TRUE)

```
  
  
```{r tarefasAtrasadas, echo=FALSE, message=FALSE, warning=FALSE}
tarefas <- read_excel("tarefas Bitrix.xlsx")

tarefas$Deadline <- as.Date(x = tarefas$Deadline, format = "%d/%m/%Y")
tarefas$`Responsible person` <- as.factor(x = tarefas$`Responsible person`)

importantPeople <- as.factor(c("Julia Couto",
                     "Daniel Eloi",
                     "Andressa Morais",
                     "Laura Vianna",
                     "Carlos Carvalho",
                     "Henrique Rocha",
                     "Vitor Almeida",
                     "Leandro Rangel",
                     "Diego Stehling",
                     "Pedro Gonçalvez",
                     "Alysson Vidotti", 
                     "Pedro Gonçalves",
                     "Francine Marinho",
                     "Gustavo Fernandes"
                     ))
  
tarefasAtrasadas <- tarefas %>% 
  filter(Status == "Pending", Deadline < Sys.Date())

tarefasAtrasadas <- tarefasAtrasadas%>% 
  filter(`Responsible person` %in% importantPeople)

ggplot(data = tarefasAtrasadas, mapping = aes(x = `Responsible person`)) +
  geom_bar(fill = "red", color = "black") +
  theme(axis.text.x = element_text(angle = 90, hjust = -1)) +
  geom_text(stat='count', aes(label=..count..), vjust=0.5, hjust= -1 ) +
  ggtitle("Tarefas Atrasadas") +
  xlab("Pessoa Responsável") +
  ylab("Contagem") +
  ylim(0, 55) +
  coord_flip()

```

  Tivemos muitas tarefas concentradas no Pedro, mas, numa avaliação rápida, todas são tarefas que se atrasaram neste fim de semana
  
```{r tarefas sem deal}

tarefasSemDeal <- tarefas %>% 
  filter(Status == "Pending",  is.na(CRM))

tarefasSemData <- tarefas %>% 
  filter(Status == "Pending",  is.na(Deadline))

```
  
```{r indicadores de SaaS}
custosMKT <- Fluxo_de_caixa_2020_v29_projecao <- read_delim("Fluxo de caixa 2020 v29 - projecao.csv", 
    ";", escape_double = FALSE, trim_ws = TRUE, 
    skip = 4)

names(custosMKT)[4] <-paste("categoria")

custosMKT <- custosMKT[,4:length(names(custosMKT))]

custosMKT <- custosMKT[c(-2,-3)]

custosMKT <- custosMKT %>% 
  filter(str_detect(categoria, "Marketing e Vendas"))

#transformar as entradas em números
meses_custosMKT <- (custosMKT[-1])

meses_custosMKT[meses_custosMKT=="-"]<-NA

meses_custosMKT<- sapply( meses_custosMKT, as.numeric )
  
viagensComerciaisTS <- ts(data = custosMKT[2,2:length(custosMKT)], start = c(2019, 1), frequency = 12)
```

