---
title: "Relatório mensal de vendas"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r bibliotecas, include=FALSE}
#Relatório mensal de vendas
require(dplyr)
require(readr)
require(ggplot2)
require(plotly)
library(readxl)
require(lubridate)
library(zoo)
require(forecast)
```

```{r vendas, echo=FALSE, message=FALSE, warning=FALSE, results = "hide"}
pipe_FunildeVendas<- read_delim("pipe Funil de Vendas - 20200413.csv", ";", escape_double = FALSE, locale = locale(), 
                                  trim_ws = TRUE)
not_all_na <- function(x) {!all(is.na(x))}

pipe_FunildeVendas <- pipe_FunildeVendas %>% select_if(not_all_na)

important_columns <- c("ID", 
                       "Pipeline",
                       "Fase",
                       "Responsável", 
                       "Nome do negócio", 
                       "Tipo", 
                       "Renda",
                       "Empresa", 
                       "Data de início", 
                       "Data de fechamento",
                       "Produto",
                       "Origem da Oportunidade", 
                       "Deal de:" )

pipe_FunildeVendas <- subset.data.frame(pipe_FunildeVendas, select= important_columns)

pipe_FunildeVendas <- pipe_FunildeVendas[!is.na(pipe_FunildeVendas$Pipeline) & pipe_FunildeVendas$Pipeline == "Funil de vendas",]
pipe_FunildeVendas$`Data de fechamento` <- as.Date(x = pipe_FunildeVendas$`Data de fechamento`, format = "%d/%m/%Y")
pipe_FunildeVendas$`Data de início` <- as.Date(x = pipe_FunildeVendas$`Data de início`, format = "%d/%m/%Y")
pipe_FunildeVendas$"endQuarter" <- quarters(pipe_FunildeVendas$`Data de fechamento`) 
pipe_FunildeVendas$"startQuarter" <- quarters(pipe_FunildeVendas$`Data de fechamento`)
pipe_FunildeVendas$Renda <- as.numeric(pipe_FunildeVendas$Renda)
pipe_FunildeVendas %>% 
  mutate_at(vars(Renda), funs(round(x = ., digits = 0)))

QuarterSales <- pipe_FunildeVendas%>%
  filter(Fase == "Ganho Fechado")
  
QuarterSalesSum <- QuarterSales %>% 
  group_by(`endQuarter`, Ano = format(`Data de fechamento`, "%Y" )) %>%
  summarise(Renda = sum(Renda)) 
 
 QuarterSalesSum <- QuarterSalesSum %>% 
  mutate(Rendaper1000 = Renda/1000 ) 
 
QuarterSalesSum$Rendaper1000 <- round(QuarterSalesSum$Rendaper1000, 0)

Q1SalesSum <- QuarterSalesSum %>% 
  filter(endQuarter == "Q1")

ggplot(data = Q1SalesSum, mapping = aes(x = Q1SalesSum$Ano, y = Q1SalesSum$Rendaper1000, label = Q1SalesSum$Rendaper1000))+
  geom_col(fill = "red", color = "black") +
  geom_text(size = 4,position = position_stack(vjust = 1.1)) +
  ylab("Renda em milhares de R$") +
  xlab("Ano") +
  ggtitle("Renda em Q1 de cada ano" )


#QuarterSalesCompare <- QuarterSalesSum %>%
  #filter(Ano > 2018)
```

```{r tarefasAtrasadas,echo=FALSE, message=FALSE, warning=FALSE, results = "hide"}
tarefas<- read_excel("~/Relatorio mensal de vendas - Pris/Tarefas bitrix 20200407.xlsx")

tarefas$Deadline <- as.Date(x = tarefas$Deadline, format = "%d/%m/%Y")
tarefas$`Responsible person` <- as.factor(x = tarefas$`Responsible person`)

importantPeople <- c("Julia Couto",
                     "Daniel Eloi",
                     "Andressa Morais",
                     "Laura Vianna",
                     "Carlos Carvalho",
                     "Henrique Rocha",
                     "Vitor Almeida",
                     "Leandro Rangel",
                     "Diego Stehling",
                     "Pedro Gonçalvez",
                     "Alysson Vidotti"
                     )
  
tarefasAtrasadas <- tarefas %>% 
  filter(Deadline < Sys.Date())

tarefasAtrasadas <- tarefasAtrasadas%>% 
  filter(`Responsible person` %in% importantPeople)

ggplot(data = tarefasAtrasadas, mapping = aes(x = `Responsible person`)) +
  geom_bar(fill = "red", color = "black") +
  theme(axis.text.x = element_text(angle = 90, hjust = 0.5)) +
  geom_text(stat='count', aes(label=..count..), vjust=-1, ) +
  ggtitle("Tarefas atrasadas") +
  xlab("Pessoa Responsável") +
  ylab("Contagem")+
  ylim(0,40)

```

```{r AcessosIlupi, echo=FALSE, message=FALSE, warning=FALSE, results = "hide"}
visitas_Ilupi <- read_csv("C:/Users/ed.velho/Downloads/Analytics Todos os dados do website Visitas ao site Ilupi 20170401-20200420.csv", skip = 20, col_names = c("Dia", "Sessoes"))

visitas_Ilupi$`Dia` <-  as.Date(x = visitas_Ilupi$`Dia`, format = "%d/%m/%Y")

visitas_Ilupi <- visitas_Ilupi %>% 
  filter(year(Dia) > 2017 )

visitas_Ilupi_Agregado <- visitas_Ilupi %>% 
  group_by("Data"=floor_date(Dia, "month")) %>%
  summarize(Sessoes=sum(Sessoes))

visitas_Ilupi_Agregado$Ano <- as.factor(year(visitas_Ilupi_Agregado$Data))
visitas_Ilupi_Agregado$Mes <- month(visitas_Ilupi_Agregado$Data)

  ggplot() + 
    geom_line(data = visitas_Ilupi_Agregado, aes(x = Mes, y = Sessoes, color = Ano,), size = 2) + 
    scale_x_continuous(breaks = 1:12, labels = c("Jan", "Fev", "Mar", "Abr", "Mai", "Jun","Jul", "Ago", "Set", "Out", "Nov", "Dez")) +
    labs(title = "Visitantes no site do Ilupi") +
    theme(panel.grid.minor.x = element_blank())
  
    
    
```
```{r AcessosPris, echo=FALSE, message=FALSE, warning=FALSE, results = "hide"}

Visitas_Site_Pris <- read_csv("C:/Users/ed.velho/Downloads/Visitas Site Pris - 20200424.csv", skip = 19, col_names = c("Dia", "Usuarios"))

Visitas_Site_Pris$Dia <-  as.Date(x = Visitas_Site_Pris$Dia, format = "%d/%m/%Y")

Visitas_Site_Pris$Usuarios <- as.numeric(Visitas_Site_Pris$Usuarios)

Visitas_Site_Pris <- Visitas_Site_Pris %>% 
  filter(year(Dia) > 2017 )

Visitas_Site_Pris_Agregado <- Visitas_Site_Pris %>% 
  group_by("Data"=floor_date(Dia, "month")) %>%
  summarize(Usuarios=sum(Usuarios))

Visitas_Site_Pris_Agregado$Ano <- as.factor(year(Visitas_Site_Pris_Agregado$Data))
Visitas_Site_Pris_Agregado$Mes <- month(Visitas_Site_Pris_Agregado$Data)

  ggplot() + 
    geom_line(data = Visitas_Site_Pris_Agregado, aes(x = Mes, y = Usuarios, color = Ano,), size = 2) + 
    scale_x_continuous(breaks = 1:12, labels = c("Jan", "Fev", "Mar", "Abr", "Mai", "Jun","Jul", "Ago", "Set", "Out", "Nov", "Dez")) +
    labs(title = "Visitantes no site do Site Pris") +
    theme(panel.grid.minor.x = element_blank())
  
```

